language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_2c8bc4d8982a_key -iv $encrypted_2c8bc4d8982a_iv -in .travis-secret.enc -out .travis-secret -d
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- mkdocs build
deploy:
  provider: pages
  local-dir: site
  skip-cleanup: true
  keep-history: true
  verbose: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master