site_name: 'GIMP и Inkscape'
site_description: 'Электронное учебно-методическое пособие «GIMP и Inkscape»'
copyright: '<table><tr><td><a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ru" target="_blank"><img alt="Лицензия Creative Commons" style="border-width: 0; max-width: 88px;" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br /><a href="https://github.com/mpudelta" target="_blank"><img alt="MPUDelta" style="border-width: 0; max-width: 88px;" src="https://avatars2.githubusercontent.com/u/36784205?s=200&v=4" /></a></td><td style="vertical-align:middle"><span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/InteractiveResource" property="dct:title" rel="dct:type">Электронное учебно-методическое пособие «GIMP и Inkscape»</span>, созданное командой <a xmlns:cc="http://creativecommons.org/ns#" href="https://github.com/mpudelta" property="cc:attributionName" rel="cc:attributionURL" target="_blank">MPUDelta</a>, публикуется на условиях <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.ru" target="_blank">лицензии Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International</a>.</td></tr></table>'
repo_url: 'https://github.com/mpudelta/gimp-inkscape'
repo_name: 'GitHub'
pages:
  - Аннотация: 'index.md'
  - Введение: 'introduction.md'
  - Часть 1. GIMP:
    - Глава 1. Знакомство с GIMP: 'gimp/1.md'
    - Глава 2. Цвета: 'gimp/2.md'
    - Глава 3. Слои: 'gimp/3.md'
  - Часть 2. Inkscape:
    - Глава 1. Знакомство с Inkscape: 'inkscape/1.md'
  - Заключение: 'conclusion.md'
  - Список литературы: 'bibliography.md'
theme:
  name: 'material'
  language: 'ru'
  palette:
    primary: 'green'
    accent: 'lightblue'
  font:
    text: 'Verdana'
    code: 'Lucida Console'
extra_css:
  - extra.css
extra_javascript:
  - extra.js
